"""initial schema

Revision ID: 0fb7dd02278d
Revises: 
Create Date: 2026-09-03 16:13:35.942409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb7dd02278d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('document_title', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('body_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resale_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('retained_pct', sa.Numeric(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('euro_ncap', 'bharat_ncap', 'global_ncap', name='safety_protocol'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('adult_score', sa.Numeric(), nullable=False),
    sa.Column('child_score', sa.Numeric(), nullable=False),
    sa.Column('assist_score', sa.Numeric(), nullable=False),
    sa.Column('max_score', sa.Numeric(), nullable=False),
    sa.Column('report_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['report_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('powertrain', sa.String(), nullable=False),
    sa.Column('ex_showroom_paise', sa.BigInteger(), nullable=False),
    sa.Column('price_source_id', sa.Integer(), nullable=False),
    sa.Column('launched_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['price_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_a', sa.Integer(), nullable=False),
    sa.Column('variant_b', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stale_after', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_a'], ['variants.id'], ),
    sa.ForeignKeyConstraint(['variant_b'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('availability', sa.Enum('standard', 'optional', 'unavailable', name='feature_availability'), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_num', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objection_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objection_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN spec_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN feature_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN rating_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='objection_facts_exactly_one_fact'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['objection_id'], ['objections.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['safety_ratings.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objection_facts')
    op.drop_table('specs')
    op.drop_table('features')
    op.drop_table('battle_cards')
    op.drop_table('variants')
    op.drop_table('safety_ratings')
    op.drop_table('resale_estimates')
    op.drop_table('service_centres')
    op.drop_table('models')
    op.drop_table('sources')
    op.drop_table('objections')
    op.drop_table('brands')
    # ### end Alembic commands ###
