"""add source_page to specs and features

Revision ID: 2d728ae4098f
Revises: 711e98bf4f5b
Create Date: 2026-09-04 15:04:36.621608

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d728ae4098f'
down_revision: str | Sequence[str] | None = '711e98bf4f5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('source_page', sa.Integer(), nullable=True))
    op.add_column('specs', sa.Column('source_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specs', 'source_page')
    op.drop_column('features', 'source_page')
    # ### end Alembic commands ###
